services:
  - type: web
    name: meu-servidor-bbb26
    runtime: python
    envVars:
      - key: PORT
        value: 8080
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
